on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.6
      with:
        server: ftp.alessandrosperotti.com
        username: 7980329@aruba.it
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: www.alessandrosperotti.com/
        server-dir: www.alessandrosperotti.com/
